version: '2'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: sensu-rabbitmq
    ports:
    - "8080:15672"
    restart: always
    environment:
    - "RABBITMQ_DEFAULT_USER=sensu"
    - "RABBITMQ_DEFAULT_PASS=secret"
    - "RABBITMQ_DEFAULT_VHOST=/sensu"
    #mem_limit: 1G
    #cpu_shares: 1

  redis:
    image: redis:3
    hostname: sensu-redis
    restart: always
    #mem_limit: 1G
    #cpu_shares: 1

  sensu-api:
    image: nachum234/sensu
    restart: always
    command: '/opt/sensu/bin/sensu-api -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions'
    links:
      - rabbitmq:sensu-rabbitmq
      - redis:sensu-redis

  sensu-server:
    image: nachum234/sensu
    restart: always
    command: '/opt/sensu/bin/sensu-server -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions'
    links:
      - rabbitmq:sensu-rabbitmq
      - redis:sensu-redis

  uchiwa:
    image: nachum234/uchiwa
    ports:
    - "3000:3000"
    restart: always
    command: ["/go/bin/app", "-c", "/config/config.json"]
    links:
      - sensu-api
